version: "3.7"
services:
  server:
    container_name: go_shawty
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"

  database:
    container_name: postgres_container
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    env_file: .env
    depends_on:
      - database
    ports:
      - "5050:80"
    networks:
      - default
    restart: always
volumes:
  data:
